# RKNN configuration for ARM edge devices (e.g., RK3588, RK3576)
# Optimized for low-power embedded inference on Rockchip NPU

metadata:
    version: "1.0"
    region: "cn" # ModelScope recommended for China-based edge devices
    cache_dir: "/data/lumen/models"

services:
    clip:
        enabled: true
        package: "lumen-clip"
        import:
            registry_class: "lumen_clip.service_registry.CLIPService"
            add_to_server: "lumen_clip.proto.ml_service_pb2_grpc.add_InferenceServicer_to_server"
        models:
            default:
                model: "MobileCLIP2-S2"
                runtime: "rknn"
                rknn_device: "rk3588" # Target NPU device
        default_model: "default"
        env:
            CLIP_BACKEND: "rknn"
            RKNN_BATCH_SIZE: "1" # Edge devices typically use batch_size=1
        server:
            port: 50051
            mdns:
                enabled: true
                name: "CLIP-Edge-RK3588"
                type: "_homenative-node._tcp.local."

    face:
        enabled: true
        package: "lumen-face"
        import:
            registry_class: "lumen_face.service_registry.FaceService"
            add_to_server: "lumen_face.proto.ml_service_pb2_grpc.add_InferenceServicer_to_server"
        models:
            default:
                model: "antelopev2"
                runtime: "rknn"
                rknn_device: "rk3588"
        server:
            port: 50052
            mdns:
                enabled: true
                name: "Face-Edge-RK3588"
