# 场景 6: CLIP 服务使用 RKNN Runtime (RK3588 边缘设备)
# 用途: 在 Rockchip RK3588 等 ARM 边缘设备上部署，利用 NPU 加速
# 内存占用: 极低
# 性能: NPU 硬件加速，功耗优化
# 注意: 仅支持 Linux ARM64 平台，需要安装 rknn-toolkit2

metadata:
  version: "1.0"
  region: "cn"  # 边缘设备建议使用国内源（ModelScope）
  cache_dir: "/data/lumen/models"  # 边缘设备通常使用固定路径

# 可选: Python 包依赖（如果需要自动安装）
dependencies:
  - "lumen-clip @ git+https://github.com/EdwinZhanCN/Lumen.git@main#subdirectory=lumen-clip"

services:
  clip:
    enabled: true
    package: "lumen-clip"
    import:
      registry_class: "image_classification.clip_service.CLIPService"
      add_to_server: "ml_service_pb2_grpc.add_InferenceServicer_to_server"
    models:
      default:
        model: "MobileCLIP2-S2"
        runtime: "rknn"
        rknn_device: "rk3588"  # 支持的设备: rk3566, rk3588, rk3576
        # RKNN 会自动从以下路径加载模型:
        # /data/lumen/models/MobileCLIP2-S2/rknn/rk3588/vision.rknn
        # /data/lumen/models/MobileCLIP2-S2/rknn/rk3588/text.rknn
    default_model: "default"
    env:
      # 边缘设备通常使用 batch_size=1 以减少内存占用
      BATCH_SIZE: "1"
      # RKNN 特定配置
      RKNN_TARGET: "rk3588"
      RKNN_DEVICE_ID: "0"  # NPU 设备 ID
      # 可选: 性能模式
      # RKNN_CORE_MASK: "0"  # 0=自动, 1=core0, 2=core1, 3=core2
    server:
      port: 50051
      mdns:
        enabled: true
        name: "CLIP-Edge-RK3588"
        type: "_lumen-clip._tcp.local."

# 边缘设备优化建议:
# 1. 使用 batch_size=1 减少内存占用
# 2. cache_dir 使用高速存储（如 eMMC/SSD）
# 3. 关闭不必要的 mdns 服务以节省资源
# 4. 考虑使用 systemd 管理服务自启动
