metadata:
    version: "1.0"
    region: "cn"
    cache_dir: "~/.lumen/models"

services:
    clip:
        enabled: true
        package: "lumen-clip"
        import:
            registry_class: "service_registry.service.CLIPService"
            add_to_server: "ml_service_pb2_grpc.add_InferenceServicer_to_server"
        models:
            clip_default:
                model: "MobileCLIP2-S2"
                runtime: "torch"
            bioclip_default:
                model: "bioclip-2"
                runtime: "torch"
                dataset: "TreeOfLife-10M"
        env:
            BATCH_SIZE: "8"
        server:
            port: 50051
            mdns:
                enabled: true
                name: "CLIP-Service"
