/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unified configuration schema for all Lumen ML services
 */
export interface LumenConfig {
  metadata: {
    /**
     * Configuration version (semantic versioning)
     */
    version: string;
    /**
     * Platform region selection (cn=ModelScope, other=HuggingFace)
     */
    region: "cn" | "other";
    /**
     * Model cache directory path (supports ~ expansion)
     */
    cache_dir: string;
    [k: string]: unknown;
  };
  deployment:
    | {
        mode?: "single";
        [k: string]: unknown;
      }
    | {
        mode?: "hub";
        [k: string]: unknown;
      };
  server: {
    /**
     * gRPC server port
     */
    port: number;
    /**
     * Server bind address
     */
    host?: string;
    mdns?: {
      /**
       * Enable mDNS service discovery
       */
      enabled?: boolean;
      /**
       * mDNS service name (required if enabled=true)
       */
      service_name?: string;
      [k: string]: unknown;
    };
    [k: string]: unknown;
  };
  /**
   * Service definitions
   */
  services: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^[a-z][a-z0-9_]*$".
     */
    [k: string]: {
      /**
       * Whether to load this service
       */
      enabled: boolean;
      /**
       * Python package name
       */
      package: string;
      import: {
        /**
         * Full dotted path to service registry class
         */
        registry_class: string;
        /**
         * Full dotted path to gRPC add_to_server function
         */
        add_to_server: string;
        [k: string]: unknown;
      };
      backend_settings?: BackendSettings;
      /**
       * Model configurations (alias → config)
       */
      models: {
        [k: string]: ModelConfig;
      };
      [k: string]: unknown;
    };
  };
}
/**
 * Optional settings for inference backend configuration.
 */
export interface BackendSettings {
  /**
   * Preferred device ('cuda', 'mps', 'cpu'). If null, auto-detects best available.
   */
  device?: string | null;
  /**
   * Maximum batch size for inference.
   */
  batch_size?: number;
  /**
   * List of ONNX execution providers. If null, uses ONNX Runtime defaults.
   */
  onnx_providers?: string[] | null;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^[a-z][a-z0-9_]*$".
 */
export interface ModelConfig {
  /**
   * Model repository name
   */
  model: string;
  /**
   * Model runtime type
   */
  runtime: "torch" | "onnx" | "rknn";
  /**
   * RKNN device identifier (required if runtime=rknn)
   */
  rknn_device?: string;
  /**
   * Dataset name for zero-shot classification (optional)
   */
  dataset?: string;
  [k: string]: unknown;
}
