/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/config/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Config
         * @description Generate a Lumen configuration from preset and options.
         */
        post: operations["generate_config_api_v1_config_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Config
         * @description Get the currently loaded configuration.
         */
        get: operations["get_current_config_api_v1_config_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Config
         * @description Validate a configuration.
         */
        post: operations["validate_config_api_v1_config_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/validate-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Path
         * @description Validate installation path for permissions and disk space.
         */
        post: operations["validate_path_api_v1_config_validate_path_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Config
         * @description Load and validate a configuration from file, then set it in app_state.
         */
        post: operations["load_config_api_v1_config_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/yaml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config Yaml
         * @description Get the current configuration as raw YAML string.
         */
        get: operations["get_config_yaml_api_v1_config_yaml_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hardware/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hardware Info
         * @description Get comprehensive hardware information.
         */
        get: operations["get_hardware_info_api_v1_hardware_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hardware/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Hardware Presets
         * @description List all available hardware presets.
         */
        get: operations["list_hardware_presets_api_v1_hardware_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hardware/presets/{preset_name}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Preset Drivers
         * @description Check driver status for a specific preset.
         */
        get: operations["check_preset_drivers_api_v1_hardware_presets__preset_name__check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hardware/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect Hardware
         * @description Detect available hardware and recommended preset.
         */
        post: operations["detect_hardware_api_v1_hardware_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/install/check-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Installation Path
         * @description Check if an existing installation exists at the given path.
         *
         *     Returns detailed information about what components are installed,
         *     whether the installation is complete, and the recommended action.
         */
        get: operations["check_installation_path_api_v1_install_check_path_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/install/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Install Status
         * @description Get current installation status of the system.
         */
        get: operations["get_install_status_api_v1_install_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/install/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Installation
         * @description Start a complete installation setup for the selected preset.
         *
         *     This will automatically install all required components:
         *     1. micromamba (if not present)
         *     2. conda environment (if not exists)
         *     3. required drivers for the preset
         */
        post: operations["start_installation_api_v1_install_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/install/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Install Tasks
         * @description List all installation tasks.
         */
        get: operations["list_install_tasks_api_v1_install_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/install/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Install Task
         * @description Get installation task status and progress.
         */
        get: operations["get_install_task_api_v1_install_tasks__task_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/install/tasks/{task_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Install Logs
         * @description Get installation task logs.
         */
        get: operations["get_install_logs_api_v1_install_tasks__task_id__logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Server Status
         * @description Get the current ML server status.
         *
         *     Returns detailed information about the running server including:
         *     - Running state and PID
         *     - Port and host configuration
         *     - Uptime in seconds
         *     - Health status
         *     - Configuration path
         */
        get: operations["get_server_status_api_v1_server_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Server
         * @description Start the ML server with specified configuration.
         *
         *     Args:
         *         request: Server start configuration including:
         *             - config_path: Path to the Lumen YAML configuration
         *             - port: Optional port override
         *             - host: Host address (currently unused, always 0.0.0.0)
         *             - environment: Conda environment name
         *
         *     Returns:
         *         Current server status after startup
         *
         *     Raises:
         *         HTTPException 400: If server is already running
         *         HTTPException 404: If config file not found
         *         HTTPException 500: If server fails to start
         */
        post: operations["start_server_api_v1_server_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Server
         * @description Stop the running ML server.
         *
         *     Args:
         *         request: Stop configuration including:
         *             - force: If True, force kill immediately without graceful shutdown
         *             - timeout: Maximum seconds to wait for graceful shutdown
         *
         *     Returns:
         *         Current server status after shutdown
         *
         *     Raises:
         *         HTTPException 400: If server is not running
         *         HTTPException 500: If server fails to stop
         */
        post: operations["stop_server_api_v1_server_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart Server
         * @description Restart the ML server with optional new configuration.
         *
         *     This is equivalent to stop + start, but handles the sequencing automatically.
         *
         *     Args:
         *         request: Restart configuration including:
         *             - config_path: Optional new config path (uses existing if not provided)
         *             - port: Optional new port (uses existing if not provided)
         *             - host: Host address (currently unused)
         *             - environment: Environment name
         *             - force: If True, force kill during stop
         *             - timeout: Maximum seconds to wait for graceful shutdown
         *
         *     Returns:
         *         Current server status after restart
         *
         *     Raises:
         *         HTTPException 400: If no config path available
         *         HTTPException 500: If restart fails
         */
        post: operations["restart_server_api_v1_server_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Server Logs
         * @description Get recent server logs.
         *
         *     Args:
         *         lines: Number of recent log lines to return (default: 100, 0 for all)
         *         since: Unix timestamp to filter logs (currently unused)
         *
         *     Returns:
         *         Server logs with metadata
         *
         *     Note:
         *         The 'since' parameter is reserved for future filtering implementation.
         *         Currently returns the most recent N lines from the log buffer.
         */
        get: operations["get_server_logs_api_v1_server_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{full_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Spa
         * @description Serve index.html for all SPA routes.
         */
        get: operations["serve_spa__full_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CheckInstallationPathResponse
         * @description Response for checking installation path.
         */
        CheckInstallationPathResponse: {
            /**
             * Has Existing Service
             * @default false
             */
            has_existing_service: boolean;
            service_status?: components["schemas"]["ServiceStatus"];
            /**
             * Ready To Start
             * @default false
             */
            ready_to_start: boolean;
            /**
             * Recommended Action
             * @default configure_new
             * @enum {string}
             */
            recommended_action: "start_existing" | "configure_new" | "repair";
            /**
             * Message
             * @default
             */
            message: string;
        };
        /**
         * ConfigRequest
         * @description Request to generate configuration.
         *
         *     This matches the Config class constructor parameters:
         *     - cache_dir: str
         *     - device_config: DeviceConfig (created from preset)
         *     - region: Region
         *     - service_name: str
         *     - port: int | None
         *
         *     Plus config generation method selection:
         *     - config_type: Literal["minimal", "light_weight", "basic", "brave"]
         *     - clip_model: Optional clip model for light_weight and basic configs
         * @example {
         *       "cache_dir": "~/.lumen",
         *       "clip_model": "MobileCLIP2-S2",
         *       "config_type": "light_weight",
         *       "port": 50051,
         *       "preset": "nvidia_gpu",
         *       "region": "other",
         *       "service_name": "lumen-ai"
         *     }
         */
        ConfigRequest: {
            /**
             * Cache Dir
             * @default ~/.lumen
             */
            cache_dir: string;
            /** Preset */
            preset: string;
            /** @default other */
            region: components["schemas"]["Region"];
            /**
             * Service Name
             * @default lumen-ai
             */
            service_name: string;
            /**
             * Port
             * @default 50051
             */
            port: number | null;
            /**
             * Config Type
             * @default minimal
             * @enum {string}
             */
            config_type: "minimal" | "light_weight" | "basic" | "brave";
            /** Clip Model */
            clip_model?: ("MobileCLIP2-S2" | "CN-CLIP_ViT-B-16") | ("MobileCLIP2-S4" | "CN-CLIP_ViT-L-14") | null;
        };
        /**
         * ConfigResponse
         * @description Generated configuration response.
         */
        ConfigResponse: {
            /** Success */
            success: boolean;
            /** Preset */
            preset: string;
            /** Config Path */
            config_path?: string | null;
            /** Config Content */
            config_content?: {
                [key: string]: unknown;
            } | null;
            /**
             * Message
             * @default
             */
            message: string;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * DriverCheckResponse
         * @description Driver check result for API responses.
         *
         *     Note: This is different from the internal DriverStatus enum in env_checker.py
         */
        DriverCheckResponse: {
            /** Name */
            name: string;
            /**
             * Status
             * @default missing
             * @enum {string}
             */
            status: "available" | "missing" | "incompatible";
            /**
             * Details
             * @default
             */
            details: string;
            /**
             * Installable Via Mamba
             * @default false
             */
            installable_via_mamba: boolean;
            /** Mamba Config Path */
            mamba_config_path?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HardwareInfoResponse
         * @description Complete hardware detection report for API responses.
         * @example {
         *       "all_drivers_available": false,
         *       "drivers": [],
         *       "machine": "x86_64",
         *       "missing_installable": [],
         *       "platform": "Linux",
         *       "presets": [],
         *       "processor": "x86_64",
         *       "python_version": "3.11.0",
         *       "recommended_preset": "nvidia_gpu"
         *     }
         */
        HardwareInfoResponse: {
            /** Platform */
            platform: string;
            /** Machine */
            machine: string;
            /** Processor */
            processor: string;
            /** Python Version */
            python_version: string;
            /** Presets */
            presets?: components["schemas"]["HardwarePresetResponse"][];
            /** Recommended Preset */
            recommended_preset?: string | null;
            /** Drivers */
            drivers?: components["schemas"]["DriverCheckResponse"][];
            /**
             * All Drivers Available
             * @default false
             */
            all_drivers_available: boolean;
            /** Missing Installable */
            missing_installable?: string[];
        };
        /**
         * HardwarePresetResponse
         * @description Hardware preset information for API responses.
         */
        HardwarePresetResponse: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Requires Drivers
             * @default true
             */
            requires_drivers: boolean;
            /** Runtime */
            runtime: string;
            /** Providers */
            providers?: string[];
        };
        /**
         * InstallLogsResponse
         * @description Installation task logs.
         */
        InstallLogsResponse: {
            /** Task Id */
            task_id: string;
            /** Logs */
            logs?: string[];
            /**
             * Total Lines
             * @default 0
             */
            total_lines: number;
        };
        /**
         * InstallSetupRequest
         * @description Request to start a complete installation setup.
         *
         *     This will automatically install all required components for the selected preset:
         *     - micromamba (if not present)
         *     - conda environment (if not exists)
         *     - required drivers for the preset
         * @example {
         *       "cache_dir": "~/.lumen",
         *       "environment_name": "lumen_env",
         *       "force_reinstall": false,
         *       "preset": "nvidia_gpu"
         *     }
         */
        InstallSetupRequest: {
            /** Preset */
            preset: string;
            /**
             * Cache Dir
             * @default ~/.lumen
             */
            cache_dir: string;
            /**
             * Environment Name
             * @default lumen_env
             */
            environment_name: string;
            /**
             * Force Reinstall
             * @default false
             */
            force_reinstall: boolean;
        };
        /**
         * InstallStatusResponse
         * @description Current installation status of the system.
         * @example {
         *       "drivers": {
         *         "cuda": "available",
         *         "cudnn": "missing"
         *       },
         *       "drivers_checked": true,
         *       "environment_exists": true,
         *       "environment_name": "lumen_env",
         *       "environment_path": "~/.lumen/envs/lumen_env",
         *       "micromamba_installed": true,
         *       "micromamba_path": "/usr/local/bin/micromamba",
         *       "missing_components": [
         *         "cudnn"
         *       ],
         *       "ready_for_preset": "nvidia_gpu"
         *     }
         */
        InstallStatusResponse: {
            /** Micromamba Installed */
            micromamba_installed: boolean;
            /** Micromamba Path */
            micromamba_path?: string | null;
            /** Environment Exists */
            environment_exists: boolean;
            /** Environment Name */
            environment_name?: string | null;
            /** Environment Path */
            environment_path?: string | null;
            /**
             * Drivers Checked
             * @default false
             */
            drivers_checked: boolean;
            /** Drivers */
            drivers?: {
                [key: string]: string;
            };
            /** Ready For Preset */
            ready_for_preset?: string | null;
            /** Missing Components */
            missing_components?: string[];
        };
        /**
         * InstallStep
         * @description A single step in the installation process.
         */
        InstallStep: {
            /** Name */
            name: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed" | "skipped";
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Message
             * @default
             */
            message: string;
            /** Started At */
            started_at?: number | null;
            /** Completed At */
            completed_at?: number | null;
        };
        /**
         * InstallTaskListResponse
         * @description List of installation tasks.
         */
        InstallTaskListResponse: {
            /** Tasks */
            tasks: components["schemas"]["InstallTaskResponse"][];
            /** Total */
            total: number;
        };
        /**
         * InstallTaskResponse
         * @description Installation task status and progress.
         * @example {
         *       "created_at": 1234567890,
         *       "current_step": "Installing CUDA drivers",
         *       "preset": "nvidia_gpu",
         *       "progress": 45,
         *       "status": "running",
         *       "steps": [
         *         {
         *           "message": "micromamba already installed",
         *           "name": "Check micromamba",
         *           "progress": 100,
         *           "status": "completed"
         *         },
         *         {
         *           "message": "Creating lumen_env...",
         *           "name": "Create environment",
         *           "progress": 60,
         *           "status": "running"
         *         }
         *       ],
         *       "task_id": "abc-123",
         *       "updated_at": 1234567895
         *     }
         */
        InstallTaskResponse: {
            /** Task Id */
            task_id: string;
            /** Preset */
            preset: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Current Step
             * @default
             */
            current_step: string;
            /** Steps */
            steps?: components["schemas"]["InstallStep"][];
            /** Created At */
            created_at: number;
            /** Updated At */
            updated_at: number;
            /** Completed At */
            completed_at?: number | null;
            /** Error */
            error?: string | null;
        };
        /**
         * Region
         * @description Platform region selection (cn=ModelScope, other=HuggingFace)
         * @enum {string}
         */
        Region: "cn" | "other";
        /**
         * ServerLogs
         * @description Server logs.
         */
        ServerLogs: {
            /** Logs */
            logs?: string[];
            /**
             * Total Lines
             * @default 0
             */
            total_lines: number;
            /**
             * New Lines
             * @default 0
             */
            new_lines: number;
        };
        /**
         * ServerRestartRequest
         * @description Request to restart the server.
         */
        ServerRestartRequest: {
            /** Config Path */
            config_path?: string | null;
            /** Port */
            port?: number | null;
            /** Host */
            host?: string | null;
            /**
             * Environment
             * @default lumen_env
             */
            environment: string;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /**
             * Timeout
             * @default 30
             */
            timeout: number;
        };
        /**
         * ServerStartRequest
         * @description Request to start the server.
         */
        ServerStartRequest: {
            /** Config Path */
            config_path?: string | null;
            /** Port */
            port?: number | null;
            /** Host */
            host?: string | null;
            /**
             * Environment
             * @default lumen_env
             */
            environment: string;
        };
        /**
         * ServerStatus
         * @description Server status information.
         * @example {
         *       "health": "healthy",
         *       "host": "0.0.0.0",
         *       "pid": 12345,
         *       "port": 50051,
         *       "running": true,
         *       "service_name": "lumen-ai",
         *       "uptime_seconds": 3600
         *     }
         */
        ServerStatus: {
            /**
             * Running
             * @default false
             */
            running: boolean;
            /** Pid */
            pid?: number | null;
            /**
             * Port
             * @default 50051
             */
            port: number;
            /**
             * Host
             * @default 0.0.0.0
             */
            host: string;
            /** Uptime Seconds */
            uptime_seconds?: number | null;
            /**
             * Service Name
             * @default lumen-ai
             */
            service_name: string;
            /** Config Path */
            config_path?: string | null;
            /**
             * Environment
             * @default lumen_env
             */
            environment: string;
            /**
             * Health
             * @default unknown
             * @enum {string}
             */
            health: "healthy" | "unhealthy" | "unknown";
            /** Last Error */
            last_error?: string | null;
        };
        /**
         * ServerStopRequest
         * @description Request to stop the server.
         */
        ServerStopRequest: {
            /**
             * Force
             * @default false
             */
            force: boolean;
            /**
             * Timeout
             * @default 30
             */
            timeout: number;
        };
        /**
         * ServiceStatus
         * @description Service component status.
         */
        ServiceStatus: {
            /**
             * Micromamba
             * @default false
             */
            micromamba: boolean;
            /**
             * Environment
             * @default false
             */
            environment: boolean;
            /**
             * Config
             * @default false
             */
            config: boolean;
            /**
             * Drivers
             * @default false
             */
            drivers: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate_config_api_v1_config_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_config_api_v1_config_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    validate_config_api_v1_config_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_path_api_v1_config_validate_path_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_config_api_v1_config_load_post: {
        parameters: {
            query: {
                config_path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_yaml_api_v1_config_yaml_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_hardware_info_api_v1_hardware_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareInfoResponse"];
                };
            };
        };
    };
    list_hardware_presets_api_v1_hardware_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwarePresetResponse"][];
                };
            };
        };
    };
    check_preset_drivers_api_v1_hardware_presets__preset_name__check_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverCheckResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_hardware_api_v1_hardware_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    check_installation_path_api_v1_install_check_path_get: {
        parameters: {
            query: {
                path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckInstallationPathResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_install_status_api_v1_install_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallStatusResponse"];
                };
            };
        };
    };
    start_installation_api_v1_install_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallSetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_install_tasks_api_v1_install_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallTaskListResponse"];
                };
            };
        };
    };
    get_install_task_api_v1_install_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallTaskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_install_logs_api_v1_install_tasks__task_id__logs_get: {
        parameters: {
            query?: {
                tail?: number;
            };
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallLogsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_server_status_api_v1_server_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
        };
    };
    start_server_api_v1_server_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_server_api_v1_server_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerStopRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_server_api_v1_server_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerRestartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_server_logs_api_v1_server_logs_get: {
        parameters: {
            query?: {
                lines?: number;
                since?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerLogs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    serve_spa__full_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                full_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
