/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/config/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Config
         * @description Generate a Lumen configuration from preset and options.
         */
        post: operations["generate_config_api_v1_config_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current Config
         * @description Get the currently loaded configuration.
         */
        get: operations["get_current_config_api_v1_config_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Config
         * @description Validate a configuration.
         */
        post: operations["validate_config_api_v1_config_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/validate-path": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Path
         * @description Validate installation path for permissions and disk space.
         */
        post: operations["validate_path_api_v1_config_validate_path_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Config
         * @description Load a configuration from file.
         */
        post: operations["load_config_api_v1_config_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hardware/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Hardware Info
         * @description Get comprehensive hardware information.
         */
        get: operations["get_hardware_info_api_v1_hardware_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hardware/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Hardware Presets
         * @description List all available hardware presets.
         */
        get: operations["list_hardware_presets_api_v1_hardware_presets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hardware/presets/{preset_name}/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Preset Drivers
         * @description Check driver status for a specific preset.
         */
        get: operations["check_preset_drivers_api_v1_hardware_presets__preset_name__check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hardware/detect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Detect Hardware
         * @description Detect available hardware and recommended preset.
         */
        post: operations["detect_hardware_api_v1_hardware_detect_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/install/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Tasks
         * @description List all installation tasks.
         */
        get: operations["list_tasks_api_v1_install_tasks_get"];
        put?: never;
        /**
         * Create Install Task
         * @description Create a new installation task.
         */
        post: operations["create_install_task_api_v1_install_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/install/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Task Status
         * @description Get installation task status.
         */
        get: operations["get_task_status_api_v1_install_tasks__task_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Task
         * @description Cancel a running installation task.
         */
        delete: operations["cancel_task_api_v1_install_tasks__task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Server Status
         * @description Get the ML server status.
         */
        get: operations["get_server_status_api_v1_server_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Server
         * @description Start the ML server.
         */
        post: operations["start_server_api_v1_server_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Stop Server
         * @description Stop the ML server.
         */
        post: operations["stop_server_api_v1_server_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server/restart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restart Server
         * @description Restart the ML server.
         */
        post: operations["restart_server_api_v1_server_restart_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/server/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Server Logs
         * @description Get server logs.
         */
        get: operations["get_server_logs_api_v1_server_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ConfigRequest
         * @description Request to generate configuration.
         * @example {
         *       "cache_dir": "~/.lumen",
         *       "port": 50051,
         *       "preset": "nvidia_gpu",
         *       "region": "en",
         *       "selected_services": [
         *         "ocr",
         *         "clip"
         *       ]
         *     }
         */
        ConfigRequest: {
            /** Preset */
            preset: string;
            /**
             * Region
             * @default en
             */
            region: string;
            /**
             * Cache Dir
             * @default ~/.lumen
             */
            cache_dir: string;
            /**
             * Port
             * @default 50051
             */
            port: number;
            /**
             * Service Name
             * @default lumen-ai
             */
            service_name: string;
            /** Selected Services */
            selected_services?: string[];
            /** Clip Model */
            clip_model?: string | null;
        };
        /**
         * ConfigResponse
         * @description Generated configuration response.
         */
        ConfigResponse: {
            /** Success */
            success: boolean;
            /** Preset */
            preset: string;
            /** Config Path */
            config_path?: string | null;
            /** Config Content */
            config_content?: {
                [key: string]: unknown;
            } | null;
            /**
             * Message
             * @default
             */
            message: string;
            /** Warnings */
            warnings?: string[];
        };
        /**
         * DriverStatus
         * @description Driver check result.
         */
        DriverStatus: {
            /** Name */
            name: string;
            /**
             * Status
             * @default missing
             * @enum {string}
             */
            status: "available" | "missing" | "incompatible";
            /**
             * Details
             * @default
             */
            details: string;
            /**
             * Installable Via Mamba
             * @default false
             */
            installable_via_mamba: boolean;
            /** Mamba Config Path */
            mamba_config_path?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HardwareInfo
         * @description Complete hardware detection report.
         * @example {
         *       "all_drivers_available": false,
         *       "machine": "x86_64",
         *       "platform": "Linux",
         *       "processor": "x86_64",
         *       "python_version": "3.11.0",
         *       "recommended_preset": "nvidia_gpu"
         *     }
         */
        HardwareInfo: {
            /** Platform */
            platform: string;
            /** Machine */
            machine: string;
            /** Processor */
            processor: string;
            /** Python Version */
            python_version: string;
            /** Presets */
            presets?: components["schemas"]["HardwarePreset"][];
            /** Recommended Preset */
            recommended_preset?: string | null;
            /** Drivers */
            drivers?: components["schemas"]["DriverStatus"][];
            /**
             * All Drivers Available
             * @default false
             */
            all_drivers_available: boolean;
            /** Missing Installable */
            missing_installable?: string[];
        };
        /**
         * HardwarePreset
         * @description Hardware preset information.
         */
        HardwarePreset: {
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Requires Drivers
             * @default true
             */
            requires_drivers: boolean;
            /** Runtime */
            runtime: string;
            /** Providers */
            providers?: string[];
        };
        /**
         * InstallListResponse
         * @description List of installation tasks.
         */
        InstallListResponse: {
            /** Tasks */
            tasks: components["schemas"]["InstallStatus"][];
            /** Total */
            total: number;
        };
        /**
         * InstallRequest
         * @description Request to start an installation task.
         * @example {
         *       "drivers": [
         *         "cuda",
         *         "openvino"
         *       ],
         *       "environment": "lumen_env",
         *       "task_type": "drivers"
         *     }
         */
        InstallRequest: {
            /**
             * Task Type
             * @enum {string}
             */
            task_type: "micromamba" | "environment" | "drivers" | "packages";
            /** Options */
            options?: {
                [key: string]: unknown;
            };
            /** Drivers */
            drivers?: string[];
            /** Packages */
            packages?: string[];
            /**
             * Environment
             * @default lumen_env
             */
            environment: string;
        };
        /**
         * InstallStatus
         * @description Installation task status.
         */
        InstallStatus: {
            /** Task Id */
            task_id: string;
            /** Task Type */
            task_type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed" | "cancelled";
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Message
             * @default
             */
            message: string;
            /**
             * Created At
             * @default 0
             */
            created_at: number;
            /** Updated At */
            updated_at?: number | null;
            /** Completed At */
            completed_at?: number | null;
            /** Error Details */
            error_details?: string | null;
        };
        /**
         * ServerLogs
         * @description Server logs.
         */
        ServerLogs: {
            /** Logs */
            logs?: string[];
            /**
             * Total Lines
             * @default 0
             */
            total_lines: number;
            /**
             * New Lines
             * @default 0
             */
            new_lines: number;
        };
        /**
         * ServerRestartRequest
         * @description Request to restart the server.
         */
        ServerRestartRequest: {
            /** Config Path */
            config_path?: string | null;
            /** Port */
            port?: number | null;
            /** Host */
            host?: string | null;
            /**
             * Environment
             * @default lumen_env
             */
            environment: string;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /**
             * Timeout
             * @default 30
             */
            timeout: number;
        };
        /**
         * ServerStartRequest
         * @description Request to start the server.
         */
        ServerStartRequest: {
            /** Config Path */
            config_path?: string | null;
            /** Port */
            port?: number | null;
            /** Host */
            host?: string | null;
            /**
             * Environment
             * @default lumen_env
             */
            environment: string;
        };
        /**
         * ServerStatus
         * @description Server status information.
         * @example {
         *       "health": "healthy",
         *       "host": "0.0.0.0",
         *       "pid": 12345,
         *       "port": 50051,
         *       "running": true,
         *       "service_name": "lumen-ai",
         *       "uptime_seconds": 3600
         *     }
         */
        ServerStatus: {
            /**
             * Running
             * @default false
             */
            running: boolean;
            /** Pid */
            pid?: number | null;
            /**
             * Port
             * @default 50051
             */
            port: number;
            /**
             * Host
             * @default 0.0.0.0
             */
            host: string;
            /** Uptime Seconds */
            uptime_seconds?: number | null;
            /**
             * Service Name
             * @default lumen-ai
             */
            service_name: string;
            /** Config Path */
            config_path?: string | null;
            /**
             * Environment
             * @default lumen_env
             */
            environment: string;
            /**
             * Health
             * @default unknown
             * @enum {string}
             */
            health: "healthy" | "unhealthy" | "unknown";
            /** Last Error */
            last_error?: string | null;
        };
        /**
         * ServerStopRequest
         * @description Request to stop the server.
         */
        ServerStopRequest: {
            /**
             * Force
             * @default false
             */
            force: boolean;
            /**
             * Timeout
             * @default 30
             */
            timeout: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    generate_config_api_v1_config_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_config_api_v1_config_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    validate_config_api_v1_config_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_path_api_v1_config_validate_path_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_config_api_v1_config_load_post: {
        parameters: {
            query: {
                config_path: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_hardware_info_api_v1_hardware_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwareInfo"];
                };
            };
        };
    };
    list_hardware_presets_api_v1_hardware_presets_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HardwarePreset"][];
                };
            };
        };
    };
    check_preset_drivers_api_v1_hardware_presets__preset_name__check_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                preset_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverStatus"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    detect_hardware_api_v1_hardware_detect_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_tasks_api_v1_install_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallListResponse"];
                };
            };
        };
    };
    create_install_task_api_v1_install_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_task_status_api_v1_install_tasks__task_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstallStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_task_api_v1_install_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_server_status_api_v1_server_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
        };
    };
    start_server_api_v1_server_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerStartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stop_server_api_v1_server_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerStopRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    restart_server_api_v1_server_restart_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerRestartRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_server_logs_api_v1_server_logs_get: {
        parameters: {
            query?: {
                lines?: number;
                since?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServerLogs"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
